# versionは自動で補完してくれるのでいらないらしい
# version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: simplyz20241211.azurecr.io/dev-frontend:latest
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: simplyz20241211.azurecr.io/dev-backend:latest
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DB_API_URL=http://golang:8080
    volumes:
      - ./backend:/app
    command: python app.py
    networks:
      - db-networks

  postgres:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: simplyz20241211.azurecr.io/dev-postgres:latest
    volumes:
      - ./database/db_data:/var/lib/postgres/data
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - db-networks

  golang:
    build:
      context: ./golang
      dockerfile: Dockerfile
    image: simplyz20241211.azurecr.io/dev-golang:latest
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres
    command: go run .
    networks:
      - db-networks

networks:
  db-networks:
    driver: bridge
